CREATE TABLE salary_update_log (
    log_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   NUMBER,
    old_salary    NUMBER,
    new_salary    NUMBER,
    log_user    VARCHAR2(100),
    log_date    DATE DEFAULT SYSDATE
);
/